import type {BlockCapability} from './types';

/**
 * Canonical block metadata — the single source of truth for scene blocks.
 * Imported by:
 * - `src/compositions/blocks/registry.ts` (attaches renderers)
 * - `web/src/utils/blocks.ts` (UI helpers)
 * - `/api/v1/capabilities` (machine-readable registry)
 *
 * Keep JSON-safe: no React renderers, no Remotion imports here.
 */
export const blockCapabilities: BlockCapability[] = [
  {
    id: 'product-intro',
    name: 'Product Intro',
    description: 'Launch headline with product visual.',
    icon: 'PL',
    category: 'intro',
    compatibleSchemas: ['ProductLaunch'],
    contentFields: [
      {key: 'headlineTemplate', label: 'Headline', type: 'text', placeholder: 'Introducing {{product_name}}', essential: true},
      {key: 'taglineTemplate', label: 'Tagline', type: 'text', placeholder: '{{tagline}}'},
    ],
    defaultDurationFrames: 120,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['product', 'intro'],
    exampleUses: ['Product launch opening scene'],
  },
  {
    id: 'features-grid',
    name: 'Features Grid',
    description: 'Three-column feature highlights.',
    icon: 'FG',
    category: 'feature',
    compatibleSchemas: ['ProductLaunch'],
    contentFields: [
      {key: 'feature1Template', label: 'Feature 1', type: 'text', placeholder: '{{feature1}}', essential: true},
      {key: 'feature2Template', label: 'Feature 2', type: 'text', placeholder: '{{feature2}}'},
      {key: 'feature3Template', label: 'Feature 3', type: 'text', placeholder: '{{feature3}}'},
    ],
    defaultDurationFrames: 140,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['product', 'features'],
    exampleUses: ['Feature comparison scene'],
  },
  {
    id: 'pricing-card',
    name: 'Pricing Card',
    description: 'Centered offer and CTA card.',
    icon: 'PC',
    category: 'cta',
    compatibleSchemas: ['ProductLaunch'],
    contentFields: [
      {key: 'taglineTemplate', label: 'Tagline', type: 'text', placeholder: '{{tagline}}', essential: true},
      {key: 'ctaText', label: 'Call to Action', type: 'text', placeholder: 'Get Started Today'},
    ],
    defaultDurationFrames: 80,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['product', 'cta', 'pricing'],
    exampleUses: ['Offer and call-to-action scene'],
  },
  {
    id: 'property-hero',
    name: 'Property Hero',
    description: 'Listing headline, image, and price.',
    icon: 'PH',
    category: 'intro',
    compatibleSchemas: ['RealEstate'],
    contentFields: [
      {key: 'headlineTemplate', label: 'Property Name', type: 'text', placeholder: '{{property_name}}', essential: true},
      {key: 'taglineTemplate', label: 'Tagline', type: 'text', placeholder: '{{tagline}}'},
      {key: 'priceTemplate', label: 'Price', type: 'text', placeholder: '{{price}}'},
    ],
    defaultDurationFrames: 150,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['real-estate', 'property', 'intro'],
    exampleUses: ['Property listing opening scene'],
  },
  {
    id: 'property-details',
    name: 'Property Details',
    description: 'Specs, location, and agent line.',
    icon: 'PD',
    category: 'detail',
    compatibleSchemas: ['RealEstate'],
    contentFields: [
      {key: 'specsLine', label: 'Specs Line', type: 'text', placeholder: '{{bedrooms}} bed · {{bathrooms}} bath · {{sqft}} sq ft', essential: true},
      {key: 'locationLine', label: 'Location', type: 'text', placeholder: '{{location}}'},
    ],
    defaultDurationFrames: 140,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['real-estate', 'property', 'details'],
    exampleUses: ['Specs and location scene'],
  },
  {
    id: 'agent-cta',
    name: 'Agent CTA',
    description: 'Agent-branded call to action.',
    icon: 'AC',
    category: 'cta',
    compatibleSchemas: ['RealEstate'],
    contentFields: [
      {key: 'ctaText', label: 'Call to Action', type: 'text', placeholder: 'Schedule a Viewing', essential: true},
    ],
    defaultDurationFrames: 50,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['real-estate', 'cta', 'agent'],
    exampleUses: ['Agent closing call-to-action scene'],
  },
  {
    id: 'social-hook',
    name: 'Social Hook',
    description: 'Bold opening hook.',
    icon: 'SH',
    category: 'hook',
    compatibleSchemas: ['SocialClip'],
    contentFields: [
      {key: 'hookTemplate', label: 'Hook', type: 'text', placeholder: '{{hook}}', essential: true},
    ],
    defaultDurationFrames: 100,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['social', 'hook'],
    exampleUses: ['Short-form video opening hook'],
  },
  {
    id: 'social-body',
    name: 'Social Body',
    description: 'Short-form body copy scene.',
    icon: 'SB',
    category: 'body',
    compatibleSchemas: ['SocialClip'],
    contentFields: [
      {key: 'bodyTemplate', label: 'Body', type: 'text', placeholder: '{{body}}', essential: true},
    ],
    defaultDurationFrames: 150,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['social', 'body'],
    exampleUses: ['Short-form video body scene'],
  },
  {
    id: 'social-outro',
    name: 'Social Outro',
    description: 'Fast closing CTA.',
    icon: 'SO',
    category: 'outro',
    compatibleSchemas: ['SocialClip'],
    contentFields: [
      {key: 'ctaText', label: 'Call to Action', type: 'text', placeholder: '{{cta}}', essential: true},
    ],
    defaultDurationFrames: 90,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['social', 'outro', 'cta'],
    exampleUses: ['Short-form video closing CTA'],
  },
  {
    id: 'brand-frame',
    name: 'Brand Frame',
    description: 'Reusable branded end frame.',
    icon: 'BF',
    category: 'outro',
    compatibleSchemas: ['any'],
    contentFields: [
      {key: 'ctaText', label: 'Call to Action', type: 'text', placeholder: 'Get Started Today'},
    ],
    defaultDurationFrames: 90,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor', 'logoUrl'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['brand', 'outro'],
    exampleUses: ['Reusable branded end frame for any video'],
  },
  {
    id: 'text-overlay',
    name: 'Text Overlay',
    description: 'Centered text over a branded background.',
    icon: 'TO',
    category: 'body',
    compatibleSchemas: ['any'],
    contentFields: [
      {key: 'headline', label: 'Headline', type: 'text', placeholder: '{{headline}}', essential: true},
      {key: 'backgroundColor', label: 'Background Color', type: 'color', placeholder: '#F7FAFC'},
    ],
    defaultDurationFrames: 120,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['text', 'generic'],
    exampleUses: ['Generic text scene over branded background'],
  },
  {
    id: 'data-callout',
    name: 'Data Callout',
    description: 'Large value with a supporting label.',
    icon: 'DC',
    category: 'feature',
    compatibleSchemas: ['any'],
    contentFields: [
      {key: 'value', label: 'Value', type: 'text', placeholder: '{{value}}', essential: true},
      {key: 'label', label: 'Label', type: 'text', placeholder: '{{label}}'},
    ],
    defaultDurationFrames: 120,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['data', 'stats', 'generic'],
    exampleUses: ['Large statistic or data point scene'],
  },
  {
    id: 'media-image',
    name: 'Media Image',
    description: 'Configurable image with cover/contain/fit modes, focal point, and overlays.',
    icon: 'MI',
    category: 'feature',
    compatibleSchemas: ['any'],
    contentFields: [
      {key: 'imageUrl', label: 'Image URL', type: 'image', placeholder: '{{primary_image_url}}', essential: true},
      {key: 'altText', label: 'Alt Text', type: 'text', placeholder: 'Descriptive text'},
    ],
    supportsImageTreatment: true,
    defaultDurationFrames: 120,
    requiredBrandSettings: ['brandColor', 'secondaryColor', 'accentColor', 'backgroundType', 'backgroundColor'],
    supportedAnimations: ['none'],
    version: '1.0.0',
    status: 'enabled',
    tags: ['image', 'media', 'generic'],
    exampleUses: ['Property photo scene', 'Product showcase scene', 'Speaker headshot scene'],
    mediaFields: ['image1', 'image2', 'backgroundImage'],
    defaultImageTreatment: {
      fit: 'cover',
      horizontalPosition: 'center',
      verticalPosition: 'center',
    },
  },
];

export const blockCapabilityById = (id: string): BlockCapability | undefined =>
  blockCapabilities.find((block) => block.id === id);

export const isBlockEnabled = (id: string): boolean => {
  const block = blockCapabilityById(id);
  return block !== undefined && block.status === 'enabled';
};
