import type {TemplateCapability} from './types';

/**
 * Canonical template metadata — the single source of truth.
 * Imported by:
 * - `src/templates/registry.ts` (attaches Zod schema + Remotion runtime props)
 * - `web/src/utils/templates.ts` (re-exports for UI compatibility)
 * - `/api/v1/capabilities` (machine-readable registry)
 *
 * Keep this JSON-safe: no Zod schemas, no Remotion imports, no default props
 * that pull in render code. Runtime concerns attach in `src/templates/registry.ts`.
 */
export const templateCapabilities: TemplateCapability[] = [
  {
    id: 'InsuranceAd',
    name: 'Insurance Ad',
    description: 'Personalized quote ads for local insurance campaigns.',
    category: 'ad',
    useCase: 'Insurance, Finance',
    supportedFormats: ['16:9', '1:1', '9:16', '4:5'],
    requiredPlaceholders: ['age', 'gender', 'location', 'company'],
    optionalPlaceholders: ['brand_color', 'secondary_color', 'accent_color', 'background_color', 'logo_url', 'background_image_url'],
    copyFields: [
      {id: 'headlineTemplate', label: 'Headline', default: 'Are you a {{age}} year old {{gender}} in {{location}}?'},
      {id: 'subheadlineTemplate', label: 'Subheadline', default: 'Get covered today with {{company}}'},
      {id: 'ctaText', label: 'Call to Action', default: 'Get a Quote Today'},
    ],
    defaultBlocks: ['product-intro', 'features-grid', 'pricing-card', 'brand-frame'],
    previewImage: null,
    version: '1.0.0',
    status: 'enabled',
    tags: ['insurance', 'finance', 'quote', 'local'],
    mediaFields: ['logo', 'backgroundImage'],
  },
  {
    id: 'ProductLaunch',
    name: 'Product Launch',
    description: 'Showcase a new product with punchy feature highlights.',
    category: 'product',
    useCase: 'SaaS, Product, Startup',
    supportedFormats: ['16:9', '1:1', '9:16', '4:5'],
    requiredPlaceholders: ['product_name', 'tagline', 'feature1', 'feature2', 'feature3', 'company'],
    optionalPlaceholders: ['brand_color', 'secondary_color', 'accent_color', 'background_color', 'logo_url', 'background_image_url', 'image1_url', 'image2_url', 'product_image_url'],
    copyFields: [
      {id: 'headlineTemplate', label: 'Headline', default: 'Introducing {{product_name}}'},
      {id: 'taglineTemplate', label: 'Tagline', default: '{{tagline}}'},
      {id: 'feature1Template', label: 'Feature 1', default: '{{feature1}}'},
      {id: 'feature2Template', label: 'Feature 2', default: '{{feature2}}'},
      {id: 'feature3Template', label: 'Feature 3', default: '{{feature3}}'},
      {id: 'ctaText', label: 'Call to Action', default: 'Get Started Today'},
    ],
    defaultBlocks: ['product-intro', 'features-grid', 'pricing-card', 'brand-frame'],
    previewImage: null,
    version: '1.0.0',
    status: 'enabled',
    tags: ['saas', 'product', 'startup', 'launch'],
    mediaFields: ['image1', 'logo', 'backgroundImage'],
  },
  {
    id: 'RealEstate',
    name: 'Real Estate',
    description: 'Property showcase videos for listings and agents.',
    category: 'property',
    useCase: 'Real Estate, Property',
    supportedFormats: ['16:9', '1:1', '9:16', '4:5'],
    requiredPlaceholders: ['property_name', 'tagline', 'price', 'bedrooms', 'bathrooms', 'sqft', 'location', 'agent'],
    optionalPlaceholders: ['brand_color', 'secondary_color', 'accent_color', 'background_color', 'logo_url', 'background_image_url', 'image1_url', 'person1_url', 'property_image_url', 'agent_image_url'],
    copyFields: [
      {id: 'headlineTemplate', label: 'Property Name', default: '{{property_name}}'},
      {id: 'taglineTemplate', label: 'Tagline', default: '{{tagline}}'},
      {id: 'priceTemplate', label: 'Price', default: '{{price}}'},
      {id: 'specsLine', label: 'Specs Line', default: '{{bedrooms}} bed · {{bathrooms}} bath · {{sqft}} sq ft'},
      {id: 'locationLine', label: 'Location', default: '{{location}}'},
      {id: 'ctaText', label: 'Call to Action', default: 'Schedule a Viewing'},
    ],
    defaultBlocks: ['property-hero', 'property-details', 'agent-cta', 'brand-frame'],
    previewImage: null,
    version: '1.0.0',
    status: 'enabled',
    tags: ['real-estate', 'property', 'listing', 'agent'],
    mediaFields: ['image1', 'person1', 'logo', 'backgroundImage'],
  },
  {
    id: 'SocialClip',
    name: 'Social Clip',
    description: 'Short-form social ads with bold hooks and fast CTA pacing.',
    category: 'social',
    useCase: 'Social, Creator, DTC',
    supportedFormats: ['16:9', '1:1', '9:16', '4:5'],
    requiredPlaceholders: ['hook', 'body', 'cta', 'brand'],
    optionalPlaceholders: ['brand_color', 'secondary_color', 'accent_color', 'background_color', 'logo_url', 'background_image_url', 'person2_url', 'speaker_image_url'],
    copyFields: [
      {id: 'hookTemplate', label: 'Hook', default: '{{hook}}'},
      {id: 'bodyTemplate', label: 'Body', default: '{{body}}'},
      {id: 'ctaText', label: 'Call to Action', default: '{{cta}}'},
    ],
    defaultBlocks: ['social-hook', 'social-body', 'social-outro', 'brand-frame'],
    previewImage: null,
    version: '1.0.0',
    status: 'enabled',
    tags: ['social', 'creator', 'dtc', 'short-form'],
    mediaFields: ['person2', 'logo', 'backgroundImage'],
  },
  {
    id: 'WebinarPromo',
    name: 'Webinar Promo',
    description: 'Promote live webinars, product demos, and online workshops.',
    category: 'social',
    useCase: 'B2B, Webinars, Events, Thought Leadership',
    supportedFormats: ['16:9', '1:1', '9:16', '4:5'],
    requiredPlaceholders: ['eventTitle', 'hostName', 'eventDate', 'eventTime', 'audience', 'keyTakeaway', 'ctaText', 'brandName'],
    optionalPlaceholders: ['brand_color', 'secondary_color', 'accent_color', 'background_color', 'logo_url', 'background_image_url', 'person2_url', 'speaker_image_url'],
    copyFields: [
      {id: 'eventTitleTemplate', label: 'Event Title', default: 'Build a repeatable content engine'},
      {id: 'hostNameTemplate', label: 'Host Name', default: 'Hosted by {{hostName}}'},
      {id: 'eventDateTemplate', label: 'Event Date', default: '{{eventDate}}'},
      {id: 'eventTimeTemplate', label: 'Event Time', default: '{{eventTime}}'},
      {id: 'audienceTemplate', label: 'Audience', default: 'For {{audience}}'},
      {id: 'keyTakeawayTemplate', label: 'Key Takeaway', default: '{{keyTakeaway}}'},
      {id: 'ctaText', label: 'Call to Action', default: 'Reserve your seat'},
      {id: 'brandName', label: 'Brand Name', default: '{{brandName}}'},
    ],
    defaultBlocks: ['text-overlay', 'data-callout', 'brand-frame'],
    previewImage: null,
    version: '1.0.0',
    status: 'enabled',
    tags: ['webinar', 'b2b', 'event', 'promo'],
    mediaFields: ['person2', 'logo', 'backgroundImage'],
  },
  {
    id: 'Testimonial',
    name: 'Testimonial',
    description: 'Customer testimonial videos with quote and attribution.',
    category: 'ad',
    useCase: 'Social Proof, Reviews, Case Studies',
    supportedFormats: ['16:9', '1:1', '9:16', '4:5'],
    requiredPlaceholders: ['quote', 'customer_name', 'company'],
    optionalPlaceholders: ['brand_color', 'secondary_color', 'accent_color', 'background_color', 'logo_url', 'background_image_url', 'person1_url', 'customer_image_url'],
    copyFields: [
      {id: 'quoteTemplate', label: 'Quote', default: '{{quote}}'},
      {id: 'customerNameTemplate', label: 'Customer Name', default: '{{customer_name}}'},
      {id: 'customerTitleTemplate', label: 'Customer Title', default: '{{customer_title}}'},
      {id: 'ctaText', label: 'Call to Action', default: 'See More Reviews'},
    ],
    defaultBlocks: ['text-overlay', 'data-callout', 'brand-frame'],
    previewImage: null,
    version: '1.0.0',
    status: 'disabled', // pending Remotion composition implementation
    tags: ['testimonial', 'review', 'social-proof', 'quote'],
    mediaFields: ['person1', 'logo', 'backgroundImage'],
  },
  {
    id: 'EventPromo',
    name: 'Event Promo',
    description: 'Promote conferences, meetups, and live events with bold visuals.',
    category: 'social',
    useCase: 'Events, Conferences, Meetups, Launches',
    supportedFormats: ['16:9', '1:1', '9:16', '4:5'],
    requiredPlaceholders: ['event_name', 'event_date', 'event_location', 'cta'],
    optionalPlaceholders: ['brand_color', 'secondary_color', 'accent_color', 'background_color', 'logo_url', 'background_image_url', 'image1_url'],
    copyFields: [
      {id: 'eventNameTemplate', label: 'Event Name', default: '{{event_name}}'},
      {id: 'eventDateTemplate', label: 'Date', default: '{{event_date}}'},
      {id: 'eventLocationTemplate', label: 'Location', default: '{{event_location}}'},
      {id: 'highlightTemplate', label: 'Highlight', default: '{{highlight}}'},
      {id: 'ctaText', label: 'Call to Action', default: 'Get Tickets'},
    ],
    defaultBlocks: ['social-hook', 'text-overlay', 'data-callout', 'brand-frame'],
    previewImage: null,
    version: '1.0.0',
    status: 'disabled', // pending Remotion composition implementation
    tags: ['event', 'conference', 'meetup', 'promo', 'tickets'],
    mediaFields: ['image1', 'logo', 'backgroundImage'],
  },
  {
    id: 'YouTubeIntro',
    name: 'YouTube Intro',
    description: 'Punchy video intros for YouTube channels and series.',
    category: 'product',
    useCase: 'YouTube, Content Creator, Series',
    supportedFormats: ['16:9', '9:16'],
    requiredPlaceholders: ['channel_name', 'series_name'],
    optionalPlaceholders: ['brand_color', 'secondary_color', 'accent_color', 'background_color', 'logo_url', 'background_image_url', 'image1_url'],
    copyFields: [
      {id: 'channelNameTemplate', label: 'Channel Name', default: '{{channel_name}}'},
      {id: 'seriesNameTemplate', label: 'Series Name', default: '{{series_name}}'},
      {id: 'episodeTitleTemplate', label: 'Episode Title', default: '{{episode_title}}'},
      {id: 'hookTemplate', label: 'Hook', default: '{{hook}}'},
      {id: 'ctaText', label: 'Call to Action', default: 'Subscribe'},
    ],
    defaultBlocks: ['social-hook', 'text-overlay', 'data-callout', 'brand-frame'],
    previewImage: null,
    version: '1.0.0',
    status: 'disabled', // pending Remotion composition implementation
    tags: ['youtube', 'intro', 'creator', 'series', 'content'],
    mediaFields: ['image1', 'logo', 'backgroundImage'],
  },
];

export const templateCapabilityById = (id: string): TemplateCapability | undefined =>
  templateCapabilities.find((template) => template.id === id);
